name: Docker Image CI

on:
  push:
    branches: [ master ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_ID }}
      run: | 
        echo $SUPER_SECRET
# docker build . --file Dockerfile --tag my-image-name:$(date +%s)
