name: Docker Image CI

on:
  push:
    branches: [ master ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        ID: ${{ secrets.DOCKER_ID }}
        PASSWD: ${{ secrets.DOCKER_PASSWD }}  
      run: | 
        docker login -u $ID -p $PASSWD
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
# 
